import { Inter } from "next/font/google";
import "./globals.css";
import SidePanel from "../components/SidePanel";
import { AntdRegistry } from "@ant-design/nextjs-registry";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <div style={{ display: "flex" }}>
            <SidePanel />
            <div style={{ width: "100%", height: "100%" }}>{children}</div>
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
