import { Inter } from "next/font/google";
import "./globals.css";
import SidePanel from "../../components/SidePanel";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{display:'flex'}} className={inter.className}>
        <SidePanel/>
        <div style={{width:'100%',height:"100%"}}>
        {children}
        </div>
        </body>
    </html>
  );
}
